defaults: &defaults
  working_directory: ~/code
  docker:
    - image: cimg/node:18.13.0-browsers

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          name: Save node modules
          key: node_modules-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Lint checks
          command: npm run ci

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node modules
          keys:
            - node_modules-{{ arch }}-{{ checksum "package-lock.json" }}

      - run:
          name: Publish to NPM
          command: npm run ci:publish

workflows:
  version: 2
  ci:
    jobs:
      - setup
      - tests:
          requires:
            - setup
      - publish:
          requires:
            - tests
          filters:
            branches:
              only: master
