name: 'Detox CI Tests'
on: [pull_request]

jobs:
  tests:
    name: 'Running tests'
    runs-on: 'macOS-latest'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Setup - Install NPM Dependencies
        run: npm ci
      - name: Setup - Install CocoaPods CLI
        run: sudo gem install cocoapods -v 1.8.4
      - name: Run tests
        run: npm run ci
